
export const DATA = [
    {
        "id": 1,
        "category": "E Class",
        "name": "New E 180 (V1)",
        "model": "Citan",
        "color": ["Đen Obsidian", "Ghế da Artico: màu Nâu"],
        "price": "2.159.000.000",
        "year": 2020,
        "material": "Xăng",
        "speed": "223 km/h",
        "size": [4.93, 1.87, 1.46],
        "weight": "2.295 kg",
        "imageUrl": ["https://mercedes-vietnamstar.com.vn/wp-content/uploads/2021/07/New-E-180-black-1-768x432.png", 'https://mercedes-vietnamstar.com.vn/wp-content/uploads/2021/07/New-E-180-black-3-768x432.png', 'https://mercedes-vietnamstar.com.vn/wp-content/uploads/2021/07/New-E-180-black-4-768x432.png'],
        "chair": 5,

        "description": [
            "Tấm che bảo vệ gầm",
            "Hệ thống PARKTRONIC",
            "Gương chiếu hậu bên ngoài chỉnh & gập điện",
            "Lốp xe dành cho mùa hè",
            "túi khí cho đầu gối người lái",
            "Camera lùi",
            "Lốp xe runflat",
            "Hệ thống phanh chủ động Active Brake Assist",
            "Tấm che nắng 2 bên cho hàng ghế trước",
            "Hệ thống tự động bảo vệ PRE-SAFE®",
            "Hệ thống cảnh báo áp suất lốp",
            "Hệ thống cảnh báo điểm mù",
            "Cổng sạc 5V (USB) cho hàng ghế sau",
            "Thảm sàn",
            "Hệ thống giải trí thế hệ mới MBUX",
            "Chức năng cửa hít",
            "Hệ thống điều hòa cho xứ nóng",
            "Đèn viền nội thất có thể điều chỉnh 64 màu sắc & độ sáng",
            "Touchpad điều khiển cảm ứng dạng thiết kế mới trên bệ trung tâm",
            "Màn che nắng cho cửa sổ hai bên phía sau",
            "Gương chiếu hậu chống chói tự động",
            "Hệ thống treo thích ứng AGILITY CONTROL",
            "Các tính năng cho hệ thống giải trí trên xe",
            "Đệm hơi tựa lưng ghế",
            "Đèn phanh Adaptive nhấp nháy khi phanh gấp",
            "Đường gân dập nổi trên nắp ca pô",
            "Bình nhiên liệu cỡ lớn",
            "Cốp đóng mở bằng điện",
            "Hộc đựng cốc nước",
            "Ốp gỗ piano bệ trung tâm màu đen",
            "Màn che nắng kính sau chỉnh điện",
            "GPS ANTENNA",
            "Cụm đèn trước LED toàn phần (Full-LED) tích hợp đèn LED chiếu sáng ban ngày",
            "Ốp bệ cửa phát sáng",
            "Tính năng gập ghế sau để chở đồ",
            "Tay lái đa chức năng bọc da",
            "Hộp số tự động 9 cấp 9G-TRONIC",
            "Điều hòa khí hậu tự động 2 vùng THERMATIC",
            "Ambient lighting",
            "Lẫy chuyển số bán tự động DIRECT SELECT phía sau tay lái",
            "Màn hình màu 12.3 inch",
            "Cụm chuyển đổi DYNAMIC SELECT với nhiều chế độ vận hành"
        ],
        "intro": "Mẫu sedan hạng sang cỡ trung Mercedes-Benz E 180 ứng dụng ngôn ngữ thiết kế mới “Sensual Purity” mang nhiều góc cạnh đầy cuốn hút, thể hiện được nét đẹp hiện đại và sang trọng. E 180 phiên bản nâng cấp mới đã chính thức có mặt tại hệ thống đại lý Vietnam Star, trở thành mảnh ghép không thể thiếu nhằm hoàn thiện danh mục sản phẩm mới trong dòng E-Class tại Việt Nam, bên cạnh E 200 Exclusive và E 300 AMG thế hệ nâng cấp mới đã có mặt tại thị trường xe sang Việt Nam vào cuối tháng 3/2021. E 180 có giá bán không thay đổi ở mức 2,050 tỷ đồng (đã bao gồm VAT)."
    },
    {
        "id": 2,
        "category": "E Class",
        "name": "New E 200 Exclusive (V1)",
        "model": "Citan",
        "color": ["Trắng", "Ghế da Artico: màu Nâu"],
        "price": "2.540.000.000",
        "year": 2023,
        "material": "Xăng",
        "speed": "240 km/h",
        "size": [4.930, 1.852, 1.468],
        "weight": "2.315 kg",
        "imageUrl": ["https://mercedes-vietnamstar.com.vn/wp-content/uploads/2021/07/New-E200-Exclusive-w-2-768x432.png", "https://mercedes-vietnamstar.com.vn/wp-content/uploads/2021/07/New-E200-Exclusive-w-4-768x432.png", "https://mercedes-vietnamstar.com.vn/wp-content/uploads/2021/07/New-E200-Exclusive-w-3-768x432.png"],
        "chair": 5,
        "intro": "Các mẫu xe chủ lực của thương hiệu Mercedes-Benz tại thị trường Việt Nam, nếu kể đến đó chính là mẫu xe E-Class đây là dòng xe đầu tiên của thương hiệu, sở hữu thiết kế Sensual Purity thế hệ mới. Cụm đèn chiếu sáng khá thon gọn, và được mở rộng về chiều ngang. Phiên bản E 200 Exclusive sẽ được trang bị công nghệ LED High Performance tiêu chuẩn. Thiết kế đèn hậu của dòng xe E-Class mang đậm phong cách của dòng xe S-Class.",
        "description": ["Hệ thống treo AGILITY CONTROL", "Tấm che bảo vệ gầm", "Màn che nắng kính sau chỉnh điện", "Touchpad điều khiển cảm ứng dạng thiết kế mới trên bệ trung tâm", "Hệ thống tự động bảo vệ PRE-SAFE®", "Hệ thống cảnh báo áp suất lốp", "Bình nhiên liệu cỡ lớn", "Đèn viền nội thất có thể điều chỉnh 64 màu sắc & độ sáng", "Camera 360 độ", "túi khí cho đầu gối người lái", "Tấm che nắng 2 bên cho hàng ghế trước", "Lốp xe runflat", "Thảm sàn", "Điều hòa khí hậu tự động THERMOTRONIC cho hàng ghế trước", "Chức năng sạc không dây", "Lẫy chuyển số bán tự động DIRECT SELECT phía sau tay lái", "Hộc đựng cốc nước", "Tay lái đa chức năng bọc da", "Chức năng cửa hít", "Màn hình màu 12.3 inch", "Hệ thống điều hòa cho xứ nóng", "Cụm đèn trước LED toàn phần (Full-LED) tích hợp đèn LED chiếu sáng ban ngày", "Hệ thống khóa xe thông minh & khởi động bằng nút bấm KEYLESS-GO", "Chức năng mở cốp sau từ xa bằng khóa điện tử", "Cụm chuyển đổi DYNAMIC SELECT với nhiều chế độ vận hành", "Ốp bệ bước cửa trước với dòng chữ “Mercedes-Benz” phát sáng", "Gương chiếu hậu chống chói tự động", "Hộp số tự động 9 cấp 9G-TRONIC", "Mặt táp-lô & thành cửa bọc da ARTICO", "Ốp gỗ nội thất màu nâu", "Màn che nắng cho cửa sổ hai bên phía sau", "Hệ thống loa cao cấp Burmester", "Lốp xe dành cho mùa hè", "Đệm hơi tựa lưng ghế", "Gói thiết kế ngoại thất sang trọng Exclusive", "Gương chiếu hậu bên ngoài chỉnh & gập điện", "Hệ thống cảnh báo điểm mù", "Ambient lighting", "Hệ thống PARKTRONIC",
            "Tính năng gập ghế sau để chở đồ"],
    },
    {
        "id": 3,
        "category": "E Class",
        "name": "E 300 AMG (V1)",
        "model": "Citan",
        "color": ["Trắng Polar", "Ghế da Nappa: màu Nâu Saddle"],
        "price": "3.129.000.000",
        "year": 2020,
        "material": "Xăng",
        "speed": "250 km/h",
        "size": [4.930, 1.852, 1.460],
        "weight": "2.295 kg",
        "imageUrl": ["https://mercedes-vietnamstar.com.vn/wp-content/uploads/2021/07/New-E300-AMG-de-1-768x432.png", "https://mercedes-vietnamstar.com.vn/wp-content/uploads/2021/07/New-E300-AMG-de-3-768x432.png", "https://mercedes-vietnamstar.com.vn/wp-content/uploads/2021/07/New-E300-AMG-de-2-768x432.png"],
        "chair": 5,
        "intro": "Mercedes-Benz E 300 AMG có kích thước tổng thể DxRxC lần lượt là 4950 x 1852 x 1460 mm. So với E 200 Exclusive, E 300 AMG dài hơn 20 mm và thấp hơn 8 mm. Đặc biệt, E 300 AMG 2021 còn sở hữu gói ngoại thất thể thao AMG giúp khẳng định cá tính riêng của phiên bản này.",
        "description": ["Tay lái thể thao bọc da Nappa với nút điều khiển cảm ứng", "Mặt táp-lô & thành cửa bọc da ARTICO", "Ốp bệ cửa phát sáng", "Màn che nắng cho cửa sổ hai bên phía sau", "Cửa sổ trời siêu rộng Panorama", "Cụm chuyển đổi DYNAMIC SELECT với nhiều chế độ vận hành", "Hệ thống bật/tắt đèn pha chủ động", "Hệ thống điều hòa cho xứ nóng", "Hệ thống PARKTRONIC", "Các tính năng cho hệ thống giải trí trên xe", "túi khí cho đầu gối người lái", "Ăng-ten GPS", "Bình nhiên liệu cỡ lớn", "Lẫy chuyển số bán tự động DIRECT SELECT phía sau tay lái", "Chức năng sạc không dây", "Gói thiết kế AMG", "Cụm đèn pha Multi-Beam LED", "Camera 360 độ", "Hệ thống PARKTRONIC", "Đệm hơi tựa lưng ghế", "Tấm che nắng 2 bên cho hàng ghế trước", "Chức năng cửa hít", "Hệ thống treo AGILITY CONTROL", "Hộc đựng cốc nước", "Tiếng động cơ thể thao", "Màn che nắng kính sau chỉnh điện", "Hệ thống giải trí thế hệ mới MBUX", "Gương chiếu hậu bên ngoài chỉnh & gập điện", "Ốp gỗ open pore bệ trung tâm màu đen", "Tấm che bảo vệ gầm", "Hệ thống dẫn đường & định vị vệ tinh toàn cầu GPS tích hợp bản đồ Việt Nam", "Hệ thống tự động bảo vệ PRE-SAFE®", "Lốp xe dành cho mùa hè", "Hệ thống loa cao cấp Burmester", "Lốp xe runflat", "Ambient lighting", "Màn hình giải trí 12.3 inch", "Hốc bánh xe mở rộng", "Đường gân dập nổi trên nắp ca pô", "Hệ thống phanh chủ động Active Brake Assist", "Điều hòa khí hậu tự động THERMOTRONIC cho hàng ghế trước", "Cụm đèn trước Multi-Beam LED tích hợp đèn LED chiếu sáng ban ngày", "Cổng sạc 5V (USB) cho hàng ghế sau", "Tính năng gập ghế sau để chở đồ", "Hệ thống cảnh báo áp suất lốp", "Hộp số tự động 9 cấp 9G-TRONIC", "Thảm sàn AMG", "Đèn viền nội thất có thể điều chỉnh 64 màu sắc & độ sáng", "BODYSHELL LOAD INCREMENT 2", "Touchpad điều khiển cảm ứng dạng thiết kế mới trên bệ trung tâm", "Chức năng mở cốp sau từ xa bằng khóa điện tử", "Hệ thống khóa xe thông minh & khởi động bằng nút bấm KEYLESS-GO"]
    },
    {
        "id": 4,
        "category": "E Class",
        "name": "New E 300 AMG (V2) ",
        "model": "Citan",
        "color": ["Đen Obsidian", "Ghế da Artico: màu Nâu"],
        "price": "2.159.000.000",
        "year": 2020,
        "material": "Xăng",
        "speed": "223 km/h",
        "size": [4.93, 1.87, 1.46],
        "weight": "2.295 kg",
        "imageUrl": ["https://mercedess-benz.com.vn/wp-content/uploads/2021/09/iris-6.webp"],
        "chair": 5,
        "description": [
            "Tấm che bảo vệ gầm",
            "Hệ thống PARKTRONIC",
            "Gương chiếu hậu bên ngoài chỉnh & gập điện",
            "Lốp xe dành cho mùa hè",
            "túi khí cho đầu gối người lái",
            "Camera lùi",
            "Lốp xe runflat",
            "Hệ thống phanh chủ động Active Brake Assist",
            "Tấm che nắng 2 bên cho hàng ghế trước",
            "Hệ thống tự động bảo vệ PRE-SAFE®",
            "Hệ thống cảnh báo áp suất lốp",
            "Hệ thống cảnh báo điểm mù",
            "Cổng sạc 5V (USB) cho hàng ghế sau",
            "Thảm sàn",
            "Hệ thống giải trí thế hệ mới MBUX",
            "Chức năng cửa hít",
            "Hệ thống điều hòa cho xứ nóng",
            "Đèn viền nội thất có thể điều chỉnh 64 màu sắc & độ sáng",
            "Touchpad điều khiển cảm ứng dạng thiết kế mới trên bệ trung tâm",
            "Màn che nắng cho cửa sổ hai bên phía sau",
            "Gương chiếu hậu chống chói tự động",
            "Hệ thống treo thích ứng AGILITY CONTROL",
            "Các tính năng cho hệ thống giải trí trên xe",
            "Đệm hơi tựa lưng ghế",
            "Đèn phanh Adaptive nhấp nháy khi phanh gấp",
            "Đường gân dập nổi trên nắp ca pô",
            "Bình nhiên liệu cỡ lớn",
            "Cốp đóng mở bằng điện",
            "Hộc đựng cốc nước",
            "Ốp gỗ piano bệ trung tâm màu đen",
            "Màn che nắng kính sau chỉnh điện",
            "GPS ANTENNA",
            "Cụm đèn trước LED toàn phần (Full-LED) tích hợp đèn LED chiếu sáng ban ngày",
            "Ốp bệ cửa phát sáng",
            "Tính năng gập ghế sau để chở đồ",
            "Tay lái đa chức năng bọc da",
            "Hộp số tự động 9 cấp 9G-TRONIC",
            "Điều hòa khí hậu tự động 2 vùng THERMATIC",
            "Ambient lighting",
            "Lẫy chuyển số bán tự động DIRECT SELECT phía sau tay lái",
            "Màn hình màu 12.3 inch",
            "Cụm chuyển đổi DYNAMIC SELECT với nhiều chế độ vận hành"
        ]
    }
]


export const CATEGORIES = [
    {
        "id": 1,
        "name": "S-Class",
        "url": "https://mercedesbenzsaigon.com/wp-content/uploads/2022/06/S450-L-New.png"
    },
    {
        "id": 2,
        "name": "C-Class",
        "url": "https://mercedesbenzsaigon.com/wp-content/uploads/2022/06/icon-c300.png"
    },
    {
        "id": 3,
        "name": "E-Class",
        "url": "https://mercedesbenzsaigon.com/wp-content/uploads/2020/12/E-180-W-removebg-preview.png"
    },
    {
        "id": 4,
        "name": "GLS",
        "url": "https://mercedesbenzsaigon.com/wp-content/uploads/2020/12/GLS-450-EM-1-removebg-preview.png"
    },
    {
        "id": 5,
        "name": "GLE",
        "url": "https://mercedesbenzsaigon.com/wp-content/uploads/2021/12/gls.png"
    },
    {
        "id": 6,
        "name": "GLC",
        "url": "https://mercedesbenzsaigon.com/wp-content/uploads/2022/06/GLC_300_Coupe.png"
    }
]
