
export const DATA = [
    {
        "id": 1,
        "category": "E Class",
        "name": "New E 180 (V1)",
        "model": "Citan",
        "color": ["Đen Obsidian", "Ghế da Artico: màu Nâu"],
        "price": "2.159.000.000",
        "year": 2020,
        "material": "Xăng",
        "speed": "223 km/h",
        "size": [4.93, 1.87, 1.46],
        "weight": "2.295 kg",
        "imageUrl": ["https://mercedes-vietnamstar.com.vn/wp-content/uploads/2021/07/New-E-180-black-1-768x432.png", 'https://mercedes-vietnamstar.com.vn/wp-content/uploads/2021/07/New-E-180-black-3-768x432.png', 'https://mercedes-vietnamstar.com.vn/wp-content/uploads/2021/07/New-E-180-black-4-768x432.png'],
        "chair": 5,

        "description": [
            "Tấm che bảo vệ gầm",
            "Hệ thống PARKTRONIC",
            "Gương chiếu hậu bên ngoài chỉnh & gập điện",
            "Lốp xe dành cho mùa hè",
            "túi khí cho đầu gối người lái",
            "Camera lùi",
            "Lốp xe runflat",
            "Hệ thống phanh chủ động Active Brake Assist",
            "Tấm che nắng 2 bên cho hàng ghế trước",
            "Hệ thống tự động bảo vệ PRE-SAFE®",
            "Hệ thống cảnh báo áp suất lốp",
            "Hệ thống cảnh báo điểm mù",
            "Cổng sạc 5V (USB) cho hàng ghế sau",
            "Thảm sàn",
            "Hệ thống giải trí thế hệ mới MBUX",
            "Chức năng cửa hít",
            "Hệ thống điều hòa cho xứ nóng",
            "Đèn viền nội thất có thể điều chỉnh 64 màu sắc & độ sáng",
            "Touchpad điều khiển cảm ứng dạng thiết kế mới trên bệ trung tâm",
            "Màn che nắng cho cửa sổ hai bên phía sau",
            "Gương chiếu hậu chống chói tự động",
            "Hệ thống treo thích ứng AGILITY CONTROL",
            "Các tính năng cho hệ thống giải trí trên xe",
            "Đệm hơi tựa lưng ghế",
            "Đèn phanh Adaptive nhấp nháy khi phanh gấp",
            "Đường gân dập nổi trên nắp ca pô",
            "Bình nhiên liệu cỡ lớn",
            "Cốp đóng mở bằng điện",
            "Hộc đựng cốc nước",
            "Ốp gỗ piano bệ trung tâm màu đen",
            "Màn che nắng kính sau chỉnh điện",
            "GPS ANTENNA",
            "Cụm đèn trước LED toàn phần (Full-LED) tích hợp đèn LED chiếu sáng ban ngày",
            "Ốp bệ cửa phát sáng",
            "Tính năng gập ghế sau để chở đồ",
            "Tay lái đa chức năng bọc da",
            "Hộp số tự động 9 cấp 9G-TRONIC",
            "Điều hòa khí hậu tự động 2 vùng THERMATIC",
            "Ambient lighting",
            "Lẫy chuyển số bán tự động DIRECT SELECT phía sau tay lái",
            "Màn hình màu 12.3 inch",
            "Cụm chuyển đổi DYNAMIC SELECT với nhiều chế độ vận hành"
        ],
        "intro": "Mẫu sedan hạng sang cỡ trung Mercedes-Benz E 180 ứng dụng ngôn ngữ thiết kế mới “Sensual Purity” mang nhiều góc cạnh đầy cuốn hút, thể hiện được nét đẹp hiện đại và sang trọng. E 180 phiên bản nâng cấp mới đã chính thức có mặt tại hệ thống đại lý Vietnam Star, trở thành mảnh ghép không thể thiếu nhằm hoàn thiện danh mục sản phẩm mới trong dòng E-Class tại Việt Nam, bên cạnh E 200 Exclusive và E 300 AMG thế hệ nâng cấp mới đã có mặt tại thị trường xe sang Việt Nam vào cuối tháng 3/2021. E 180 có giá bán không thay đổi ở mức 2,050 tỷ đồng (đã bao gồm VAT)."
    },
    {
        "id": 2,
        "category": "E Class",
        "name": "New E 200 Exclusive (V1)",
        "model": "Citan",
        "color": ["Trắng", "Ghế da Artico: màu Nâu"],
        "price": "2.540.000.000",
        "year": 2023,
        "material": "Xăng",
        "speed": "240 km/h",
        "size": [4.930, 1.852, 1.468],
        "weight": "2.315 kg",
        "imageUrl": ["https://mercedes-vietnamstar.com.vn/wp-content/uploads/2021/07/New-E200-Exclusive-w-2-768x432.png", "https://mercedes-vietnamstar.com.vn/wp-content/uploads/2021/07/New-E200-Exclusive-w-4-768x432.png", "https://mercedes-vietnamstar.com.vn/wp-content/uploads/2021/07/New-E200-Exclusive-w-3-768x432.png"],
        "chair": 5,
        "intro": "Các mẫu xe chủ lực của thương hiệu Mercedes-Benz tại thị trường Việt Nam, nếu kể đến đó chính là mẫu xe E-Class đây là dòng xe đầu tiên của thương hiệu, sở hữu thiết kế Sensual Purity thế hệ mới. Cụm đèn chiếu sáng khá thon gọn, và được mở rộng về chiều ngang. Phiên bản E 200 Exclusive sẽ được trang bị công nghệ LED High Performance tiêu chuẩn. Thiết kế đèn hậu của dòng xe E-Class mang đậm phong cách của dòng xe S-Class.",
        "description": ["Hệ thống treo AGILITY CONTROL", "Tấm che bảo vệ gầm", "Màn che nắng kính sau chỉnh điện", "Touchpad điều khiển cảm ứng dạng thiết kế mới trên bệ trung tâm", "Hệ thống tự động bảo vệ PRE-SAFE®", "Hệ thống cảnh báo áp suất lốp", "Bình nhiên liệu cỡ lớn", "Đèn viền nội thất có thể điều chỉnh 64 màu sắc & độ sáng", "Camera 360 độ", "túi khí cho đầu gối người lái", "Tấm che nắng 2 bên cho hàng ghế trước", "Lốp xe runflat", "Thảm sàn", "Điều hòa khí hậu tự động THERMOTRONIC cho hàng ghế trước", "Chức năng sạc không dây", "Lẫy chuyển số bán tự động DIRECT SELECT phía sau tay lái", "Hộc đựng cốc nước", "Tay lái đa chức năng bọc da", "Chức năng cửa hít", "Màn hình màu 12.3 inch", "Hệ thống điều hòa cho xứ nóng", "Cụm đèn trước LED toàn phần (Full-LED) tích hợp đèn LED chiếu sáng ban ngày", "Hệ thống khóa xe thông minh & khởi động bằng nút bấm KEYLESS-GO", "Chức năng mở cốp sau từ xa bằng khóa điện tử", "Cụm chuyển đổi DYNAMIC SELECT với nhiều chế độ vận hành", "Ốp bệ bước cửa trước với dòng chữ “Mercedes-Benz” phát sáng", "Gương chiếu hậu chống chói tự động", "Hộp số tự động 9 cấp 9G-TRONIC", "Mặt táp-lô & thành cửa bọc da ARTICO", "Ốp gỗ nội thất màu nâu", "Màn che nắng cho cửa sổ hai bên phía sau", "Hệ thống loa cao cấp Burmester", "Lốp xe dành cho mùa hè", "Đệm hơi tựa lưng ghế", "Gói thiết kế ngoại thất sang trọng Exclusive", "Gương chiếu hậu bên ngoài chỉnh & gập điện", "Hệ thống cảnh báo điểm mù", "Ambient lighting", "Hệ thống PARKTRONIC",
            "Tính năng gập ghế sau để chở đồ"],
    },
    {
        "id": 3,
        "category": "E Class",
        "name": "E 300 AMG (V1)",
        "model": "Citan",
        "color": ["Trắng Polar", "Ghế da Nappa: màu Nâu Saddle"],
        "price": "3.129.000.000",
        "year": 2020,
        "material": "Xăng",
        "speed": "250 km/h",
        "size": [4.930, 1.852, 1.460],
        "weight": "2.295 kg",
        "imageUrl": ["https://mercedes-vietnamstar.com.vn/wp-content/uploads/2021/07/New-E300-AMG-de-1-768x432.png", "https://mercedes-vietnamstar.com.vn/wp-content/uploads/2021/07/New-E300-AMG-de-3-768x432.png", "https://mercedes-vietnamstar.com.vn/wp-content/uploads/2021/07/New-E300-AMG-de-2-768x432.png"],
        "chair": 5,
        "intro": "Mercedes-Benz E 300 AMG có kích thước tổng thể DxRxC lần lượt là 4950 x 1852 x 1460 mm. So với E 200 Exclusive, E 300 AMG dài hơn 20 mm và thấp hơn 8 mm. Đặc biệt, E 300 AMG 2021 còn sở hữu gói ngoại thất thể thao AMG giúp khẳng định cá tính riêng của phiên bản này.",
        "description": ["Tay lái thể thao bọc da Nappa với nút điều khiển cảm ứng", "Mặt táp-lô & thành cửa bọc da ARTICO", "Ốp bệ cửa phát sáng", "Màn che nắng cho cửa sổ hai bên phía sau", "Cửa sổ trời siêu rộng Panorama", "Cụm chuyển đổi DYNAMIC SELECT với nhiều chế độ vận hành", "Hệ thống bật/tắt đèn pha chủ động", "Hệ thống điều hòa cho xứ nóng", "Hệ thống PARKTRONIC", "Các tính năng cho hệ thống giải trí trên xe", "túi khí cho đầu gối người lái", "Ăng-ten GPS", "Bình nhiên liệu cỡ lớn", "Lẫy chuyển số bán tự động DIRECT SELECT phía sau tay lái", "Chức năng sạc không dây", "Gói thiết kế AMG", "Cụm đèn pha Multi-Beam LED", "Camera 360 độ", "Hệ thống PARKTRONIC", "Đệm hơi tựa lưng ghế", "Tấm che nắng 2 bên cho hàng ghế trước", "Chức năng cửa hít", "Hệ thống treo AGILITY CONTROL", "Hộc đựng cốc nước", "Tiếng động cơ thể thao", "Màn che nắng kính sau chỉnh điện", "Hệ thống giải trí thế hệ mới MBUX", "Gương chiếu hậu bên ngoài chỉnh & gập điện", "Ốp gỗ open pore bệ trung tâm màu đen", "Tấm che bảo vệ gầm", "Hệ thống dẫn đường & định vị vệ tinh toàn cầu GPS tích hợp bản đồ Việt Nam", "Hệ thống tự động bảo vệ PRE-SAFE®", "Lốp xe dành cho mùa hè", "Hệ thống loa cao cấp Burmester", "Lốp xe runflat", "Ambient lighting", "Màn hình giải trí 12.3 inch", "Hốc bánh xe mở rộng", "Đường gân dập nổi trên nắp ca pô", "Hệ thống phanh chủ động Active Brake Assist", "Điều hòa khí hậu tự động THERMOTRONIC cho hàng ghế trước", "Cụm đèn trước Multi-Beam LED tích hợp đèn LED chiếu sáng ban ngày", "Cổng sạc 5V (USB) cho hàng ghế sau", "Tính năng gập ghế sau để chở đồ", "Hệ thống cảnh báo áp suất lốp", "Hộp số tự động 9 cấp 9G-TRONIC", "Thảm sàn AMG", "Đèn viền nội thất có thể điều chỉnh 64 màu sắc & độ sáng", "BODYSHELL LOAD INCREMENT 2", "Touchpad điều khiển cảm ứng dạng thiết kế mới trên bệ trung tâm", "Chức năng mở cốp sau từ xa bằng khóa điện tử", "Hệ thống khóa xe thông minh & khởi động bằng nút bấm KEYLESS-GO"]
    },
    {
        "id": 4,
        "category": "S Class",
        "name": "S 450 4MATIC",
        "model": "Citan",
        "color": ["Đen", "Ghế da Nappa màu Vàng Macchiato"],
        "price": "5.039.000.000",
        "year": 2022,
        "material": "Xăng",
        "speed": "250 km/h",
        "size": [5.289, 1.954, 1.503],
        "weight": "2.025 kg",
        "imageUrl": ["https://mercedesbenzsaigon.com/wp-content/uploads/2022/06/S450-L-New.png", "https://mercedes-vietnamstar.com.vn/wp-content/uploads/2022/03/S-450-4MATIC-den-07-768x432.jpg", "https://mercedes-vietnamstar.com.vn/wp-content/uploads/2022/03/S-450-4MATIC-den-07-768x432.jpg"],
        "chair": 5,
        "intro": "Mercedes-Benz S450 2022 có thân hình to lớn hơn đôi chút với kích thước tổng thể DxRxC lần lượt là 5300 x 1937 x 1503 mm. Nhờ đó không gian nội thất đã được mở rộng thêm.",
        "description": ["Đèn viền nội thất", "Khóa đai an toàn thiết kế mới", "Hệ thống hiển thị áp suất lốp", "túi khí cho người ngồi ở hàng ghế sau", "Chức năng massage cho ghế sau", "Hệ thống dẫn đường & định vị vệ tinh toàn cầu GPS tích hợp bản đồ Việt Nam", "Ổ cắm điện 12V", "Cụm đèn trước Multibeam LED", "Màn che nắng cho cửa sổ hai bên phía sau chỉnh điện", "Tính năng hỗ trợ giữ khoảng cách chủ động DISTRONIC", "Chức năng sạc không dây cho ghế sau", "Cảm biến quét vân tay", "Các tính năng cho hệ thống giải trí trên xe", "PRE-SAFE® impulse", "Tính năng massage bắp chân cho hàng ghế sau", "Ốp bệ trung tâm màu Đen Crystal-Look", "Kết nối Android Auto", "Seat heating Plus for driver and front passenger seats", "Ghế trước có thể gấp gọn", "Tựa đầu cỡ lớn, điều chỉnh được", "seat heating Plus for outer rear seats", "Chức năng HANDS-FREE ACCESS", "Chức năng sạc không dây", "Màn che nắng kính sau chỉnh điện", "Tính năng khóa cốp an toàn từ bên trong xe", "Tuỳ chọn cá nhân hoá âm thanh", "Sách hướng dẫn sử dụng bằng tiếng Việt", "Tấm che nắng 2 bên cho hàng ghế trước", "Cốp đóng mở bằng điện", "Điều hòa khí hậu tự động THERMOTRONIC cho hàng ghế trước", "2 tai nghe không dây cao cấp", "Điều hòa khí hậu tự động THERMOTRONIC cho hàng ghế sau", "Hệ thống giải trí đa phương tiện MBUX", "Hệ thống sưởi & thông gió cho hàng ghế trước", "tính năng bật tắt đèn pha chủ động", "Túi khí bên hông cho ghế sau", "Tính năng ngắt kích hoạt túi khí trước", "Kết nối Apple Carplay", "Ốp bệ cửa phát sáng", "PRE-SAFE® impulse side", "kính xe cách âm, cách nhiệt và phản xạ tia hồng ngoại", "Tính năng KEYLESS-GO với tay nắm cửa dạng ẩn", "dung tích bình xăng 76 lít", "Hệ thống treo khí nén AIRMATIC", "Bộ vá lốp khẩn cấp Tirefit", "Hàng ghế sau chỉnh điện, có chức năng bộ nhớ ghế", "Thảm sàn", "Tay lái đa chức năng bọc da", "Các cổng sạc USB với chức năng sạc nhanh", "Hộp số tự động 9 cấp", "Ghế thương gia", "Tính năng hỗ trợ giữ làn đường chủ động Active Lane Keeping Assist", "Hệ thống sưởi & thông gió cho hàng ghế sau", "Lưng ghế sau gập được", "Hiển thị thông tin về dây đai của hàng ghế sau", "Hệ thống âm thanh cao cấp Burmester® 3D surround", "Cửa sổ trời siêu rộng Panoramic", "Gương chiếu hậu chống chói", "Hệ thống giải trí cao cấp MBUX High-End cho hàng ghế sau", "Gói bộ nhớ dành cho ghế sau", "Đèn chiếu logo Mercedes", "Đệm hơi tựa lưng ghế", "Màn hình trung tâm OLED", "Tấm che bảo vệ gầm", "Rear loading sill protection in stainless steel", "Chức năng cửa hít", "Tính năng sưởi vùng cổ và vai ở ghế sau"]
    },
    {
        "id": 5,
        "category": "S Class",
        "name": "S450 LUXURY",
        "model": "Citan",
        "color": ["Xanh Emerald,Đen, Đỏ", "Xanh, Đen, Be, Đỏ"],
        "price": "5.559.000.000",
        "year": 2022,
        "material": "Xăng",
        "speed": "250 km/h",
        "size": [5.289, 1.954, 1.503],
        "weight": "2.820 kg",
        "imageUrl": ["https://mercedesbenzsaigon.com/wp-content/uploads/2022/06/icon-s450-luxury.png", "https://mercedes-vietnamstar.com.vn/wp-content/uploads/2023/02/S-450-4MATIC-Luxury-Xanh-Emerald-03-768x432.jpg", "https://mercedes-vietnamstar.com.vn/wp-content/uploads/2023/02/S-450-4MATIC-Luxury-xanh-768x432.jpg"],
        "chair": 5,
        "intro": "Mercedes S450L Luxury trang bị hàng ghế trước chỉnh điện, nhớ 3 vị trí và có tựa đầu cỡ lớn. Ghế sau cũng có chức năng chỉnh điện và tựa đầu tuy nhiên bổ sung thêm bệ để chân điều chỉnh điện ngả 43,5 độ, massage 6 chế độ và đỡ bắp chân. Không chỉ vậy, cả hai hàng ghế đều có chức năng sưởi và thông gió giúp người dùng thêm thoải mái trên những quãng đường dài. Không chỉ chăm sóc hành khách về không gian khi trang bị hệ thống điều hòa 2 vùng độc lập cùng bộ lọc khí dạng Air Balance oxy hóa không khí và tạo hương thơm, xe còn có đèn viền nội thất 64 màu với 10 kiểu phối khác nhau giúp không gian càng thêm hoàn hảo.",
        "description": ["Tính năng massage bắp chân cho hàng ghế sau", "Tính năng hỗ trợ giữ khoảng cách chủ động DISTRONIC", "Chức năng điều khiển bằng cử chỉ", "Cửa sổ trời siêu rộng Panoramic", "Chức năng massage cho ghế sau", "Túi khí bên hông cho ghế sau", "Đèn chiếu logo Mercedes", "Gói ốp gỗ Exclusive", "Hệ thống treo khí nén AIRMATIC", "Tính năng hỗ trợ giữ làn đường chủ động Active Lane Keeping Assist", "Tính năng sưởi vùng cổ và vai ở ghế sau", "Hệ thống dẫn đường & định vị vệ tinh toàn cầu GPS tích hợp bản đồ Việt Nam", "Hệ thống giải trí cao cấp MBUX High-End cho hàng ghế sau", "Màn hình trung tâm OLED", "túi khí cho người ngồi ở hàng ghế sau", "Chức năng sạc không dây cho ghế sau", "Seat heating Plus for driver and front passenger seats", "Bọc trần bằng sợi cao cấp DINAMICA", "Kết nối Android Auto", "kính xe cách âm, cách nhiệt và phản xạ tia hồng ngoại", "Hệ thống sưởi & thông gió cho hàng ghế trước", "tính năng bật tắt đèn pha chủ động", "Lưng ghế sau gập được", "Hệ thống âm thanh cao cấp Burmester® 3D surround", "Ổ cắm điện 12V", "2 tai nghe không dây cao cấp", "dung tích bình xăng 76 lít", "Cốp đóng mở bằng điện", "Chức năng cửa hít", "Gói bộ nhớ dành cho ghế sau", "Tính năng ngắt kích hoạt túi khí trước", "Ghế trước có thể gấp gọn", "Bộ vá lốp khẩn cấp Tirefit", "PRE-SAFE® impulse", "Viền thép không gỉ cao cấp cho khoang hành lý", "Tay lái đa chức năng bọc da", "Hộp số tự động 9 cấp", "Đèn viền nội thất", "Chức năng sạc không dây", "Ốp bệ cửa phát sáng", "Đệm hơi tựa lưng ghế", "Tựa đầu cỡ lớn, điều chỉnh được", "Tấm che bảo vệ gầm", "Các cổng sạc USB với chức năng sạc nhanh", "Cảm biến quét vân tay", "Máy tính bảng điều khiển hệ thống MBUX cho ghế sau", "Hiển thị thông tin về dây đai của hàng ghế sau", "Điều hòa khí hậu tự động THERMOTRONIC cho hàng ghế sau", "Tính năng KEYLESS-GO với tay nắm cửa dạng ẩn", "Kết nối Apple Carplay", "PRE-SAFE® impulse side", "Ghế thương gia", "Lốp xe với bọt hấp thụ tiếng ồn", "Hệ thống sưởi & thông gió cho hàng ghế sau", "Thảm trải sàn designo", "Sách hướng dẫn sử dụng bằng tiếng Việt", "Tấm che nắng 2 bên cho hàng ghế trước", "seat heating Plus for outer rear seats", "Khóa đai an toàn thiết kế mới", "Màn che nắng kính sau chỉnh điện", "Tính năng khóa cốp an toàn từ bên trong xe", "Hàng ghế sau chỉnh điện, có chức năng bộ nhớ ghế", "Các tính năng cho hệ thống giải trí trên xe", "Điều hòa khí hậu tự động THERMOTRONIC cho hàng ghế trước", "Gương chiếu hậu chống chói", "Tuỳ chọn cá nhân hoá âm thanh", "Màn che nắng cho cửa sổ hai bên phía sau chỉnh điện", "Hệ thống giải trí đa phương tiện MBUX", "Ốp bệ trung tâm màu Đen Crystal-Look", "Hệ thống hiển thị áp suất lốp"]
    },
    {
        "id": 6,
        "category": "S Class",
        "name": "S450 MAYBACH",
        "model": "Citan",
        "color": ["Xanh Emerald", "Ghế da Nappa màu Nâu"],
        "price": "8.199.000.000",
        "year": 2022,
        "material": "Xăng",
        "speed": "250 km/h",
        "size": [5.469, 1.956, 1.510],
        "weight": "2.890 kg",
        "imageUrl": ["https://mercedesbenzsaigon.com/wp-content/uploads/2020/12/maybac-removebg-preview.png", "https://mercedes-vietnamstar.com.vn/wp-content/uploads/2023/02/Mercedes-Maybach-S-450-4MATIC-mau-Xanh-Emerald-02-768x432.jpg", "https://mercedes-vietnamstar.com.vn/wp-content/uploads/2023/02/Mercedes-Maybach-S-450-4MATIC-mau-Xanh-Emerald-06-768x432.jpg", "https://mercedes-vietnamstar.com.vn/wp-content/uploads/2023/02/Mercedes-Maybach-S-450-4MATIC-mau-Bac-High-tech-02-768x432.jpg", "https://mercedes-vietnamstar.com.vn/wp-content/uploads/2023/02/Mercedes-Maybach-S-450-4MATIC-mau-bac-Mojave-02-768x432.jpg", "https://mercedes-vietnamstar.com.vn/wp-content/uploads/2023/02/Mercedes-Maybach-S-450-4MATIC-mau-bac-Mojave-06-768x432.jpg"],
        "chair": 4,
        "intro": "Mercedes-Benz S450 2022 có thân hình to lớn hơn đôi chút với kích thước tổng thể DxRxC lần lượt là 5300 x 1937 x 1503 mm. Nhờ đó không gian nội thất đã được mở rộng thêm.",
        "description": ["Màn hình giải trí 12.3 inch", "Hệ thống dẫn đường & định vị vệ tinh toàn cầu GPS tích hợp bản đồ Việt Nam", "Head-up Display", "Hệ thống PRE-SAFE® impulse side", "Hệ thống giải trí MBUX", "Hệ thống đèn chiếu sáng thích ứng cho khoang hành lý phía sau", "chức năng sưởi ghế sau", "Ốp bệ cửa phát sáng", "Hệ thống treo khí nén AIRMATIC", "Đèn chiếu logo Mercedes", "Kết nối Apple Carplay", "Khe hút gió cản trước màu đen phủ bóng", "Các tính năng cho hệ thống giải trí trên xe", "Hệ thống bật/tắt đèn pha chủ động", "Ghế thương gia", "Túi khí phía sau", "Chức năng sưởi tựa tay cho người lái & hành khách phía trước", "Chức năng sạc không dây cho ghế sau", "Sách hướng dẫn sử dụng bằng tiếng Việt", "Chức năng cửa hít", "Màn che nắng kính sau chỉnh điện", "Màn che nắng cho cửa sổ hai bên phía sau chỉnh điện", "Cảm biến quét vân tay", "Khoá dây đai an toàn bằng chrome cao cấp với thiết kế phát sáng đặc biệt", "Hệ thống sưởi & thông gió cho hàng ghế sau", "Camera 360 độ", "Cốp đóng mở bằng điện", "Máy tính bảng điều khiển hệ thống MBUX cho ghế sau", "Chức năng massage bắp chân cho ghế thương gia phía sau", "DIGITAL LIGHT", "Chức năng hỗ trợ giữ khoảng cách an toàn DISTRONIC", "Hộp số tự động 9 cấp", "Cửa sổ trời siêu rộng Panorama", "Giá đỡ dây đai an toàn tự động điều chỉnh cho hàng ghế sau", "PRE-SAFE® impulse", "Tấm che bảo vệ gầm", "Hệ thống MAGIC VISION CONTROL với cần gạt nước mưa thích ứng & có sưởi", "2 tai nghe không dây cao cấp", "Chức năng sạc không dây", "Hệ thống hỗ trợ đánh lái bánh sau", "Chức năng điều khiển bằng cử chỉ phía sau", "Ghế trước có thể gấp gọn", "Bộ nhớ dành cho ghế sau", "Hệ thống báo động chống trộm", "Hệ thống PARKTRONIC", "Cửa sau đóng mở bằng điện", "Tính năng chống trộm được mở rộng", "Ghế sau tùy chỉnh bằng điện, có chức năng bộ nhớ", "Hệ thống khóa xe thông minh & khởi động bằng nút bấm KEYLESS-GO", "Tính năng ngắt kích hoạt túi khí trước", "Chức năng sưởi ấm cho hàng ghế trước", "Đèn viền nội thất", "Thảm sàn cao cấp", "Lốp xe với bọt hấp thụ tiếng ồn", "Hệ thống giải trí MBUX High-End cho hàng ghế sau", "Gói ốp gỗ Exclusive", "Túi khí bên hông cho ghế sau", "Bàn gấp cho ghế sau", "Túi khí dây đai", "Kính cách nhiệt khoang sau màu tối", "Bình nhiên liệu cỡ lớn", "Điều hòa khí hậu tự động THERMOTRONIC cho hàng ghế trước", "Hệ thống loa cao cấp Burmester", "Tay lái đa chức năng bọc da", "Màn hình giải trí 12.3 inch", "Cổng sạc 5V (USB type C) cho hàng ghế sau", "Hiển thị thông tin về dây đai của hàng ghế sau", "Lưng ghế sau gập được", "Kết nối Android Auto", "kính xe cách âm, cách nhiệt và phản xạ tia hồng ngoại", "Bọc trần bằng sợi cao cấp DINAMICA", "Hệ thống hiển thị áp suất lốp", "Tựa đầu cỡ lớn, điều chỉnh được", "Bảng đồng hồ kỹ thuật số sau vô lăng với màn hình 12.3-inch và hiệu ứng hiển thị 3D", "Ổ cắm điện 12V", "Hệ thống đèn viền trang trí nội thất chủ động", "Điều hòa khí hậu tự động THERMOTRONIC cho hàng ghế sau", "Chức năng HANDS-FREE ACCESS", "Hệ thống hỗ trợ giữ làn đường chủ động", "Chìa khoá thiết kế đặc biệt với viền chrome trang trí", "Chức năng sưởi ấm cho tựa đầu phía sau", "Viền thép không gỉ cao cấp cho khoang hành lý", "Chức năng sưởi ấm cổ & vai hàng ghế sau", "Khoang sau hạng nhất với 2 ghế độc lập", "Gương chiếu hậu chống chói", "Chức năng massage cho ghế sau", "Hoá chất vá lốp tạm thời TIREFIT", "Chức năng sưởi ấm vô lăng", "Tuỳ chọn cá nhân hoá âm thanh", "Tấm che nắng 2 bên cho hàng ghế trước", "Chức năng điều khiển bằng cử chỉ", "Hệ thống sưởi & thông gió cho hàng ghế trước"]
    },
    {
        "id": 7,
        "category": "S Class",
        "name": "S680 MAYBACH",
        "model": "Citan",
        "color": ["Đen", "Ghế da Nappa màu Vàng Macchiato"],
        "price": "15.990.000.000",
        "year": 2022,
        "material": "Xăng",
        "speed": "250 km/h",
        "size": [5.469, 1.921, 1.510],
        "weight": "2.890 kg",
        "imageUrl": ["https://mercedesbenzsaigon.com/wp-content/uploads/2020/12/maybac-removebg-preview.png", "https://mercedes-vietnamstar.com.vn/wp-content/uploads/2023/02/Mercedes-Maybach-S-680-4MATIC-Bac-High-tech-06-768x432.jpg", "https://mercedes-vietnamstar.com.vn/wp-content/uploads/2023/02/Mercedes-Maybach-S-680-4MATIC-Bac-Mojave-03-768x432.jpg"],
        "chair": 4,
        "intro": "Mercedes-Benz S450 2022 có thân hình to lớn hơn đôi chút với kích thước tổng thể DxRxC lần lượt là 5300 x 1937 x 1503 mm. Nhờ đó không gian nội thất đã được mở rộng thêm.",
        "description": ["Màn hình giải trí 12.3 inch", "Chức năng sạc không dây cho ghế sau", "Tính năng ngắt kích hoạt túi khí trước", "Chức năng sưởi tựa tay cho người lái & hành khách phía trước", "Hệ thống giải trí MBUX High-End cho hàng ghế sau", "Tuỳ chọn cá nhân hoá âm thanh", "Ổ cắm điện 12V", "Bảng đồng hồ kỹ thuật số sau vô lăng với màn hình 12.3-inch và hiệu ứng hiển thị 3D", "Gói ốp gỗ Exclusive", "Hệ thống dẫn đường & định vị vệ tinh toàn cầu GPS tích hợp bản đồ Việt Nam", "Đèn viền nội thất", "chức năng sưởi ghế sau", "Hiển thị thông tin về dây đai của hàng ghế sau", "Chìa khoá thiết kế đặc biệt với viền chrome trang trí", "Kết nối Android Auto", "Hệ thống hỗ trợ giữ làn đường chủ động", "Chức năng điều khiển bằng cử chỉ", "Sách hướng dẫn sử dụng bằng tiếng Việt", "Chức năng sưởi ấm cổ & vai hàng ghế sau", "Tính năng chống trộm được mở rộng", "Chức năng sạc không dây", "Điều hòa khí hậu tự động THERMOTRONIC cho hàng ghế sau", "Hệ thống giải trí MBUX", "Bộ nhớ dành cho ghế sau", "Viền thép không gỉ cao cấp cho khoang hành lý", "DIGITAL LIGHT", "Giá đỡ dây đai an toàn tự động điều chỉnh cho hàng ghế sau", "Chức năng sưởi ấm cho hàng ghế trước", "Lốp xe với bọt hấp thụ tiếng ồn", "Chức năng sưởi ấm cho tựa đầu phía sau", "Cảm biến quét vân tay", "Hệ thống bật/tắt đèn pha chủ động", "Hệ thống treo khí nén AIRMATIC", "Kết nối Apple Carplay", "2 tai nghe không dây cao cấp", "Chức năng hỗ trợ giữ khoảng cách an toàn DISTRONIC", "Lưng ghế sau gập được", "Ghế sau tùy chỉnh bằng điện, có chức năng bộ nhớ", "Hệ thống hỗ trợ đánh lái bánh sau", "Tấm che bảo vệ gầm", "Hệ thống MAGIC VISION CONTROL với cần gạt nước mưa thích ứng & có sưởi", "Chức năng massage bắp chân cho ghế thương gia phía sau", "Camera 360 độ", "Chức năng cửa hít", "Túi khí bên hông cho ghế sau", "Chức năng HANDS-FREE ACCESS", "Hệ thống hiển thị áp suất lốp", "Hệ thống PARKTRONIC", "Màn che nắng kính sau chỉnh điện", "Bàn gấp cho ghế sau", "Gương chiếu hậu chống chói", "Điều hòa khí hậu tự động THERMOTRONIC cho hàng ghế trước", "Hệ thống sưởi & thông gió cho hàng ghế trước", "Hệ thống âm thanh cao cấp Burmester high-end 3D", "Tựa đầu cỡ lớn, điều chỉnh được", "Tấm che nắng 2 bên cho hàng ghế trước", "Cốp đóng mở bằng điện", "Ốp bệ cửa phát sáng", "Head-up Display", "Tay lái đa chức năng bọc da", "Cổng sạc 5V (USB type C) cho hàng ghế sau", "Tủ lạnh cho hàng ghế sau", "PRE-SAFE® impulse", "Các tính năng cho hệ thống giải trí trên xe", "Túi khí phía sau", "Hệ thống báo động chống trộm", "Ghế thương gia", "Khoang sau hạng nhất với 2 ghế độc lập", "Đèn chiếu logo Mercedes", "Hệ thống đèn viền trang trí nội thất chủ động", "kính xe cách âm, cách nhiệt và phản xạ tia hồng ngoại", "Bình nhiên liệu cỡ lớn", "Cửa sau đóng mở bằng điện", "Hệ thống đèn chiếu sáng thích ứng cho khoang hành lý phía sau", "Chức năng massage cho ghế sau", "Hoá chất vá lốp tạm thời TIREFIT", "Cửa sổ trời siêu rộng Panorama", "Bọc trần bằng sợi cao cấp DINAMICA", "Kính cách nhiệt khoang sau màu tối", "Màn che nắng cho cửa sổ hai bên phía sau chỉnh điện", "Khoá dây đai an toàn bằng chrome cao cấp với thiết kế phát sáng đặc biệt", "Hệ thống khóa xe thông minh & khởi động bằng nút bấm KEYLESS-GO", "Hệ thống PRE-SAFE® impulse side", "Thảm sàn cao cấp", "Máy tính bảng điều khiển hệ thống MBUX cho ghế sau", "Hộp số tự động 9 cấp", "Túi khí dây đai", "Chức năng sưởi ấm vô lăng", "Ghế trước có thể gấp gọn", "Hệ thống sưởi & thông gió cho hàng ghế sau"]
    },
    {
        "id": 8,
        "category": "C Class",
        "name": "C 300 AMG 206046",
        "model": "Citan",
        "color": ["Đen", "Ghế da Artico màu Nâu"],
        "price": "2.089.000.000",
        "year": 2023,
        "material": "Xăng",
        "speed": "250 km/h",
        "size": [4.751, 1.820, 1.438],
        "weight": "1.675 kg",
        "imageUrl": ["https://mercedesbenzsaigon.com/wp-content/uploads/2022/06/icon-c300.png", "https://mercedes-vietnamstar.com.vn/wp-content/uploads/2023/02/C-300-AMG-den-Obsidian-01-768x432.jpg", "https://mercedes-vietnamstar.com.vn/wp-content/uploads/2023/02/C-300-AMG-den-Obsidian-03-768x432.jpg", "https://mercedes-vietnamstar.com.vn/wp-content/uploads/2023/02/C-300-AMG-do-Hyacinth-768x432.jpg", "https://mercedes-vietnamstar.com.vn/wp-content/uploads/2023/02/C-300-AMG-do-Hyacinth-03-768x432.jpg"],
        "chair": 5,
        "intro": "Những cải tiến về thiết kế, tiện nghi cũng như động cơ trên Mercedes C300 AMG nâng cấp đều nhằm mục đích cung cấp cho khách hàng một mẫu xe thể thao thực thụ và nhận đươc sự đánh giá cao từ cả phía chuyên gia lẫn người tiêu dùng. Trong khi giá xe Mercedes-Benz C 300 AMG tại Việt Nam hiện nay đang rất cạnh tranh, chắc chắn sẽ trở thành đối thủ “khó nhằn” ở phân khúc sedan hạng sang.",
        "description": ["Cốp đóng mở bằng điện", "Gương chiếu hậu bên ngoài chỉnh & gập điện", "Hiển thị thông tin về dây đai của hàng ghế sau", "Tay lái thể thao bọc da Nappa với nút điều khiển cảm ứng", "Tiếng động cơ thể thao", "Đèn nội thất", "Hệ thống phanh chủ động Active Brake Assist", "Camera 360 độ", "Chức năng kiểm soát tốc độ Cruise Control với SPEEDTRONIC", "Lốp xe runflat", "Tấm che nắng 2 bên cho hàng ghế trước", "Hệ thống bật/tắt đèn pha chủ động", "Hộp số tự động 9 cấp", "Ốp bệ cửa phát sáng", "Bảng đồng hồ dạng kỹ thuật số với màn hình 12.3-inch", "Hệ thống đèn viền trang trí nội thất", "Hệ thống PARKTRONIC", "Ghế trước thiết kế thể thao", "Hệ thống treo thích ứng AGILITY CONTROL", "Tấm che bảo vệ gầm", "Chức năng HANDS-FREE ACCESS", "Chức năng sạc không dây", "Đệm hơi tựa lưng ghế", "Hệ thống dẫn đường & định vị vệ tinh toàn cầu GPS tích hợp bản đồ Việt Nam", "Lưới tản nhiệt kim cương", "Gương chiếu hậu chống chói", "Hệ thống cảnh báo áp suất lốp", "Màn che nắng kính sau chỉnh điện", "Màn che nắng cho cửa sổ hai bên phía sau", "Thảm sàn AMG", "Hệ thống giải trí MBUX thế hệ mới", "Hệ thống phanh với đĩa phanh lớn phía trước", "Tựa tay trung tâm màu đen phủ bóng", "Cửa sổ trời siêu rộng Panorama", "Ghế lái xe có thể tùy chỉnh bằng điện cùng với bộ nhớ", "Các tính năng cho hệ thống giải trí trên xe", "Hệ thống cảnh báo điểm mù", "Điều hòa khí hậu tự động 2 vùng", "Sách hướng dẫn sử dụng bằng tiếng Việt", "Mặt táp-lô & dây đai an toàn bằng da ARTICO", "Gói thiết kế AMG", "DIGITAL LIGHT", "DIGITAL LIGHT", "Tuỳ chọn cá nhân hoá âm thanh", "Hệ thống khóa xe thông minh & khởi động bằng nút bấm KEYLESS-GO", "Đèn chiếu logo Mercedes", "Cần gạt nước mưa với cảm biến mưa", "Hệ thống âm thanh cao cấp Burmester® 3D surround", "Hộc đựng cốc nước", "Ghế trước chỉnh điện có bộ nhớ", "Kết nối Apple Carplay", "Tính năng gập ghế sau để chở đồ", "Màn hình giải trí 12.3 inch", "Cụm chuyển đổi DYNAMIC SELECT với nhiều chế độ vận hành", "Kết nối Android Auto"]
    },
    {
        "id": 9,
        "category": "C Class",
        "name": "C200 Avantgarde Plus",
        "model": "Citan",
        "color": ["Đen", "Ghế da Nappa màu Vàng Macchiato"],
        "price": "1.849.000.000",
        "year": 2022,
        "material": "Xăng",
        "speed": "250 km/h",
        "size": [5.469, 1.921, 1.510],
        "weight": "2.890 kg",
        "imageUrl": ["https://mercedesbenzsaigon.com/wp-content/uploads/2022/06/zyro-image-2-e1686715260686.png", "https://mercedes-vietnamstar.com.vn/wp-content/uploads/2023/02/Mercedes-Maybach-S-680-4MATIC-Bac-High-tech-06-768x432.jpg", "https://mercedes-vietnamstar.com.vn/wp-content/uploads/2023/02/Mercedes-Maybach-S-680-4MATIC-Bac-Mojave-03-768x432.jpg"],
        "chair": 4,
        "intro": "Mercedes-Benz S450 2022 có thân hình to lớn hơn đôi chút với kích thước tổng thể DxRxC lần lượt là 5300 x 1937 x 1503 mm. Nhờ đó không gian nội thất đã được mở rộng thêm.",
        "description": ["Màn hình giải trí 12.3 inch", "Chức năng sạc không dây cho ghế sau", "Tính năng ngắt kích hoạt túi khí trước", "Chức năng sưởi tựa tay cho người lái & hành khách phía trước", "Hệ thống giải trí MBUX High-End cho hàng ghế sau", "Tuỳ chọn cá nhân hoá âm thanh", "Ổ cắm điện 12V", "Bảng đồng hồ kỹ thuật số sau vô lăng với màn hình 12.3-inch và hiệu ứng hiển thị 3D", "Gói ốp gỗ Exclusive", "Hệ thống dẫn đường & định vị vệ tinh toàn cầu GPS tích hợp bản đồ Việt Nam", "Đèn viền nội thất", "chức năng sưởi ghế sau", "Hiển thị thông tin về dây đai của hàng ghế sau", "Chìa khoá thiết kế đặc biệt với viền chrome trang trí", "Kết nối Android Auto", "Hệ thống hỗ trợ giữ làn đường chủ động", "Chức năng điều khiển bằng cử chỉ", "Sách hướng dẫn sử dụng bằng tiếng Việt", "Chức năng sưởi ấm cổ & vai hàng ghế sau", "Tính năng chống trộm được mở rộng", "Chức năng sạc không dây", "Điều hòa khí hậu tự động THERMOTRONIC cho hàng ghế sau", "Hệ thống giải trí MBUX", "Bộ nhớ dành cho ghế sau", "Viền thép không gỉ cao cấp cho khoang hành lý", "DIGITAL LIGHT", "Giá đỡ dây đai an toàn tự động điều chỉnh cho hàng ghế sau", "Chức năng sưởi ấm cho hàng ghế trước", "Lốp xe với bọt hấp thụ tiếng ồn", "Chức năng sưởi ấm cho tựa đầu phía sau", "Cảm biến quét vân tay", "Hệ thống bật/tắt đèn pha chủ động", "Hệ thống treo khí nén AIRMATIC", "Kết nối Apple Carplay", "2 tai nghe không dây cao cấp", "Chức năng hỗ trợ giữ khoảng cách an toàn DISTRONIC", "Lưng ghế sau gập được", "Ghế sau tùy chỉnh bằng điện, có chức năng bộ nhớ", "Hệ thống hỗ trợ đánh lái bánh sau", "Tấm che bảo vệ gầm", "Hệ thống MAGIC VISION CONTROL với cần gạt nước mưa thích ứng & có sưởi", "Chức năng massage bắp chân cho ghế thương gia phía sau", "Camera 360 độ", "Chức năng cửa hít", "Túi khí bên hông cho ghế sau", "Chức năng HANDS-FREE ACCESS", "Hệ thống hiển thị áp suất lốp", "Hệ thống PARKTRONIC", "Màn che nắng kính sau chỉnh điện", "Bàn gấp cho ghế sau", "Gương chiếu hậu chống chói", "Điều hòa khí hậu tự động THERMOTRONIC cho hàng ghế trước", "Hệ thống sưởi & thông gió cho hàng ghế trước", "Hệ thống âm thanh cao cấp Burmester high-end 3D", "Tựa đầu cỡ lớn, điều chỉnh được", "Tấm che nắng 2 bên cho hàng ghế trước", "Cốp đóng mở bằng điện", "Ốp bệ cửa phát sáng", "Head-up Display", "Tay lái đa chức năng bọc da", "Cổng sạc 5V (USB type C) cho hàng ghế sau", "Tủ lạnh cho hàng ghế sau", "PRE-SAFE® impulse", "Các tính năng cho hệ thống giải trí trên xe", "Túi khí phía sau", "Hệ thống báo động chống trộm", "Ghế thương gia", "Khoang sau hạng nhất với 2 ghế độc lập", "Đèn chiếu logo Mercedes", "Hệ thống đèn viền trang trí nội thất chủ động", "kính xe cách âm, cách nhiệt và phản xạ tia hồng ngoại", "Bình nhiên liệu cỡ lớn", "Cửa sau đóng mở bằng điện", "Hệ thống đèn chiếu sáng thích ứng cho khoang hành lý phía sau", "Chức năng massage cho ghế sau", "Hoá chất vá lốp tạm thời TIREFIT", "Cửa sổ trời siêu rộng Panorama", "Bọc trần bằng sợi cao cấp DINAMICA", "Kính cách nhiệt khoang sau màu tối", "Màn che nắng cho cửa sổ hai bên phía sau chỉnh điện", "Khoá dây đai an toàn bằng chrome cao cấp với thiết kế phát sáng đặc biệt", "Hệ thống khóa xe thông minh & khởi động bằng nút bấm KEYLESS-GO", "Hệ thống PRE-SAFE® impulse side", "Thảm sàn cao cấp", "Máy tính bảng điều khiển hệ thống MBUX cho ghế sau", "Hộp số tự động 9 cấp", "Túi khí dây đai", "Chức năng sưởi ấm vô lăng", "Ghế trước có thể gấp gọn", "Hệ thống sưởi & thông gió cho hàng ghế sau"]
    },
    {
        "id": 10,
        "category": "GLS",
        "name": "GLS 450 4MATIC Đen",
        "model": "Citan",
        "color": ["Đen", "Ghế da Nappa màu Vàng Macchiato"],
        "price": "5.309.000.000",
        "year": 2022,
        "material": "Xăng",
        "speed": "250 km/h",
        "size": [5.226, 2.030, 1.845],
        "weight": "2.890 kg",
        "imageUrl": ["https://65e81151f52e248c552b-fe74cd567ea2f1228f846834bd67571e.ssl.cf1.rackcdn.com/ldm-images/2022-Mercedes-Benz-GLS-color-Obsidian-Black-metallic.png", "https://mercedes-vietnamstar.com.vn/wp-content/uploads/2021/09/GLS-450-4MATIC-7-768x432.png", "https://mercedes-vietnamstar.com.vn/wp-content/uploads/2021/09/GLS-450-4MATIC-6-768x432.png"],
        "chair": 7,
        "intro": "Mercedes-Benz GLS-Class  vừa chính thức được giới thiệu tại Việt Nam, đây là đối thủ cạnh tranh của BMW X7 và Lexus LX 570 ở phân khúc SUV 7 chỗ hạng sang cỡ lớn. Phiên bản được trình làng là Mercedes GLS 450 4MATIC nhập khẩu từ Mỹ với giá bán đề xuất 4,909 tỷ (đã bao gồm VAT), thấp hơn đáng kể so với X7 (7,5 tỷ) cũng như LX 570 (8,18 tỷ). Không chỉ vậy, mức giá khởi điểm của Mercedes GLS  đắt hơn Mercedes GLE 450 4MATIC   chính hãng chỉ 540 triệu. Có lẽ cạnh tranh bằng giá là vũ khí mạnh mẽ nhất của GLS, nếu so với 2 đối thủ được phân phối chính hãng bởi Thaco và Toyota Việt Nam.",
        "description": ["Màn hình giải trí 12.3 inch", "Đèn nội thất", "Các tính năng cho hệ thống giải trí trên xe", "Camera 360 độ", "Hệ thống bật/tắt đèn pha chủ động", "Cửa sổ trời siêu rộng Panorama", "Cụm đèn trước Multi-Beam LED tích hợp đèn LED chiếu sáng ban ngày", "Hệ thống loa cao cấp Burmester", "Hệ thống treo khí nén AIRMATIC", "Tấm che khoang hành lý phía sau", "Ghế trước chỉnh điện có bộ nhớ", "Chức năng sạc không dây", "Hệ thống cảnh báo áp suất lốp", "Hàng ghế thứ 3 gập điện", "Thảm sàn AMG", "Túi khí bên hông cho ghế sau", "Hệ thống khóa xe thông minh & khởi động bằng nút bấm KEYLESS-GO", "Chức năng HANDS-FREE ACCESS", "Hệ thống dẫn đường & định vị vệ tinh toàn cầu GPS tích hợp bản đồ Việt Nam", "Tay lái 3 chấu bọc da nappa và ốp gỗ, tích hợp nút điều khiển cảm ứng", "Đèn chiếu logo Mercedes", "Lốp xe dự phòng", "Chức năng đóng mở cửa sau bằng điện", "Gói thiết kế AMG", "Chức năng cửa hít", "Màn che nắng cho cửa sổ hai bên phía sau chỉnh điện", "Điều hòa khí hậu tự động THERMOTRONIC cho hàng ghế trước", "Mặt táp-lô & thành cửa bọc da ARTICO", "Tấm che nắng 2 bên cho hàng ghế trước", "Tấm che bảo vệ gầm", "Điều hòa khí hậu tự động THERMOTRONIC cho hàng ghế sau", "5+2 Seat option", "Hộp số tự động 9 cấp", "Bậc lên xuống bằng hợp kim nhôm"]
    },
    {
        "id": 11,
        "category": "GLS",
        "name": "GLS 450 4MATIC Xanh",
        "model": "Citan",
        "color": ["Xanh", "Ghế da Nappa màu Vàng Macchiato"],
        "price": "5.309.000.000",
        "year": 2022,
        "material": "Xăng",
        "speed": "250 km/h",
        "size": [5.226, 2.030, 1.845],
        "weight": "2.890 kg",
        "imageUrl": ["https://mercedes-truongchinh.com/data/upload/media/mercedes-gls450-hinhdaidien-1641187671.png", "https://mercedes-vietnamstar.com.vn/wp-content/uploads/2021/09/GLS-450-4MATIC-8-768x432.png", "https://mercedes-vietnamstar.com.vn/wp-content/uploads/2021/09/GLS-450-4MATIC-7-768x432.png", "https://mercedes-vietnamstar.com.vn/wp-content/uploads/2021/09/GLS-450-4MATIC-6-768x432.png"],
        "chair": 7,
        "intro": "Mercedes-Benz GLS-Class  vừa chính thức được giới thiệu tại Việt Nam, đây là đối thủ cạnh tranh của BMW X7 và Lexus LX 570 ở phân khúc SUV 7 chỗ hạng sang cỡ lớn. Phiên bản được trình làng là Mercedes GLS 450 4MATIC nhập khẩu từ Mỹ với giá bán đề xuất 4,909 tỷ (đã bao gồm VAT), thấp hơn đáng kể so với X7 (7,5 tỷ) cũng như LX 570 (8,18 tỷ). Không chỉ vậy, mức giá khởi điểm của Mercedes GLS  đắt hơn Mercedes GLE 450 4MATIC   chính hãng chỉ 540 triệu. Có lẽ cạnh tranh bằng giá là vũ khí mạnh mẽ nhất của GLS, nếu so với 2 đối thủ được phân phối chính hãng bởi Thaco và Toyota Việt Nam.",
        "description": ["Màn hình giải trí 12.3 inch", "Đèn nội thất", "Các tính năng cho hệ thống giải trí trên xe", "Camera 360 độ", "Hệ thống bật/tắt đèn pha chủ động", "Cửa sổ trời siêu rộng Panorama", "Cụm đèn trước Multi-Beam LED tích hợp đèn LED chiếu sáng ban ngày", "Hệ thống loa cao cấp Burmester", "Hệ thống treo khí nén AIRMATIC", "Tấm che khoang hành lý phía sau", "Ghế trước chỉnh điện có bộ nhớ", "Chức năng sạc không dây", "Hệ thống cảnh báo áp suất lốp", "Hàng ghế thứ 3 gập điện", "Thảm sàn AMG", "Túi khí bên hông cho ghế sau", "Hệ thống khóa xe thông minh & khởi động bằng nút bấm KEYLESS-GO", "Chức năng HANDS-FREE ACCESS", "Hệ thống dẫn đường & định vị vệ tinh toàn cầu GPS tích hợp bản đồ Việt Nam", "Tay lái 3 chấu bọc da nappa và ốp gỗ, tích hợp nút điều khiển cảm ứng", "Đèn chiếu logo Mercedes", "Lốp xe dự phòng", "Chức năng đóng mở cửa sau bằng điện", "Gói thiết kế AMG", "Chức năng cửa hít", "Màn che nắng cho cửa sổ hai bên phía sau chỉnh điện", "Điều hòa khí hậu tự động THERMOTRONIC cho hàng ghế trước", "Mặt táp-lô & thành cửa bọc da ARTICO", "Tấm che nắng 2 bên cho hàng ghế trước", "Tấm che bảo vệ gầm", "Điều hòa khí hậu tự động THERMOTRONIC cho hàng ghế sau", "5+2 Seat option", "Hộp số tự động 9 cấp", "Bậc lên xuống bằng hợp kim nhôm"]
    },
    {
        "id": 12,
        "category": "GLS",
        "name": "GLS 450 4MATIC Trắng",
        "model": "Citan",
        "color": ["Trắng", "Ghế da Nappa màu Vàng Macchiato"],
        "price": "5.309.000.000",
        "year": 2022,
        "material": "Xăng",
        "speed": "250 km/h",
        "size": [5.226, 2.030, 1.845],
        "weight": "2.890 kg",
        "imageUrl": ["https://mercedesbenzvn.com.vn/wp-content/uploads/2022/04/mercedes-benz-gls-450-4matic-03042022-1.png", "https://mercedes-vietnamstar.com.vn/wp-content/uploads/2021/09/GLS-450-4MATIC-12-768x432.png  ", "https://mercedes-vietnamstar.com.vn/wp-content/uploads/2021/09/GLS-450-4MATIC-1-768x432.png", "https://mercedes-vietnamstar.com.vn/wp-content/uploads/2021/09/GLS-450-4MATIC-2-768x432.png"],
        "chair": 7,
        "intro": "Mercedes-Benz GLS-Class  vừa chính thức được giới thiệu tại Việt Nam, đây là đối thủ cạnh tranh của BMW X7 và Lexus LX 570 ở phân khúc SUV 7 chỗ hạng sang cỡ lớn. Phiên bản được trình làng là Mercedes GLS 450 4MATIC nhập khẩu từ Mỹ với giá bán đề xuất 4,909 tỷ (đã bao gồm VAT), thấp hơn đáng kể so với X7 (7,5 tỷ) cũng như LX 570 (8,18 tỷ). Không chỉ vậy, mức giá khởi điểm của Mercedes GLS  đắt hơn Mercedes GLE 450 4MATIC   chính hãng chỉ 540 triệu. Có lẽ cạnh tranh bằng giá là vũ khí mạnh mẽ nhất của GLS, nếu so với 2 đối thủ được phân phối chính hãng bởi Thaco và Toyota Việt Nam.",
        "description": ["Màn hình giải trí 12.3 inch", "Đèn nội thất", "Các tính năng cho hệ thống giải trí trên xe", "Camera 360 độ", "Hệ thống bật/tắt đèn pha chủ động", "Cửa sổ trời siêu rộng Panorama", "Cụm đèn trước Multi-Beam LED tích hợp đèn LED chiếu sáng ban ngày", "Hệ thống loa cao cấp Burmester", "Hệ thống treo khí nén AIRMATIC", "Tấm che khoang hành lý phía sau", "Ghế trước chỉnh điện có bộ nhớ", "Chức năng sạc không dây", "Hệ thống cảnh báo áp suất lốp", "Hàng ghế thứ 3 gập điện", "Thảm sàn AMG", "Túi khí bên hông cho ghế sau", "Hệ thống khóa xe thông minh & khởi động bằng nút bấm KEYLESS-GO", "Chức năng HANDS-FREE ACCESS", "Hệ thống dẫn đường & định vị vệ tinh toàn cầu GPS tích hợp bản đồ Việt Nam", "Tay lái 3 chấu bọc da nappa và ốp gỗ, tích hợp nút điều khiển cảm ứng", "Đèn chiếu logo Mercedes", "Lốp xe dự phòng", "Chức năng đóng mở cửa sau bằng điện", "Gói thiết kế AMG", "Chức năng cửa hít", "Màn che nắng cho cửa sổ hai bên phía sau chỉnh điện", "Điều hòa khí hậu tự động THERMOTRONIC cho hàng ghế trước", "Mặt táp-lô & thành cửa bọc da ARTICO", "Tấm che nắng 2 bên cho hàng ghế trước", "Tấm che bảo vệ gầm", "Điều hòa khí hậu tự động THERMOTRONIC cho hàng ghế sau", "5+2 Seat option", "Hộp số tự động 9 cấp", "Bậc lên xuống bằng hợp kim nhôm"]
    },
    {
        "id": 13,
        "category": "GLS",
        "name": "GLS 450 4MATIC Maybach",
        "model": "Citan",
        "color": ["Trắng", "Da Nappa màu đen"],
        "price": "8.679.000.000",
        "year": 2022,
        "material": "Xăng",
        "speed": "250 km/h",
        "size": [5.205, 2.030, 1.838],
        "weight": "2.890 kg",
        "imageUrl": ["https://www.mercedes-benz.com.vn/content/dam/hq/passengercars/cars/gls/mercedes-maybach-gls-x167-pi/overview/modeloverview/09-2022/images/mercedes-maybach-gls-x167-modeloverview-696x392-09-2022.png", "https://imgd-ct.aeplcdn.com/1280x720/n/cw/ec/95489/maybach-gls-exterior-right-front-three-quarter-5.jpeg?isig=0&q=80", "https://images.netdirector.co.uk/gforces-auto/image/upload/q_auto,c_fill,f_auto,fl_lossy/auto-client/9d3c7514d77feab69e74f023b2fc5a30/glsmaybach.png"],
        "chair": 5,
        "intro": "Mercedes-Benz GLS-Class  vừa chính thức được giới thiệu tại Việt Nam, đây là đối thủ cạnh tranh của BMW X7 và Lexus LX 570 ở phân khúc SUV 7 chỗ hạng sang cỡ lớn. Phiên bản được trình làng là Mercedes GLS 450 4MATIC nhập khẩu từ Mỹ với giá bán đề xuất 4,909 tỷ (đã bao gồm VAT), thấp hơn đáng kể so với X7 (7,5 tỷ) cũng như LX 570 (8,18 tỷ). Không chỉ vậy, mức giá khởi điểm của Mercedes GLS  đắt hơn Mercedes GLE 450 4MATIC   chính hãng chỉ 540 triệu. Có lẽ cạnh tranh bằng giá là vũ khí mạnh mẽ nhất của GLS, nếu so với 2 đối thủ được phân phối chính hãng bởi Thaco và Toyota Việt Nam.",
        "description": ["Màn hình giải trí 12.3 inch", "Chức năng sạc không dây cho ghế sau", "Tính năng ngắt kích hoạt túi khí trước", "Chức năng sưởi tựa tay cho người lái & hành khách phía trước", "Hệ thống giải trí MBUX High-End cho hàng ghế sau", "Tuỳ chọn cá nhân hoá âm thanh", "Ổ cắm điện 12V", "Bảng đồng hồ kỹ thuật số sau vô lăng với màn hình 12.3-inch và hiệu ứng hiển thị 3D", "Gói ốp gỗ Exclusive", "Hệ thống dẫn đường & định vị vệ tinh toàn cầu GPS tích hợp bản đồ Việt Nam", "Đèn viền nội thất", "chức năng sưởi ghế sau", "Hiển thị thông tin về dây đai của hàng ghế sau", "Chìa khoá thiết kế đặc biệt với viền chrome trang trí", "Kết nối Android Auto", "Hệ thống hỗ trợ giữ làn đường chủ động", "Chức năng điều khiển bằng cử chỉ", "Sách hướng dẫn sử dụng bằng tiếng Việt", "Chức năng sưởi ấm cổ & vai hàng ghế sau", "Tính năng chống trộm được mở rộng", "Chức năng sạc không dây", "Điều hòa khí hậu tự động THERMOTRONIC cho hàng ghế sau", "Hệ thống giải trí MBUX", "Bộ nhớ dành cho ghế sau", "Viền thép không gỉ cao cấp cho khoang hành lý", "DIGITAL LIGHT", "Giá đỡ dây đai an toàn tự động điều chỉnh cho hàng ghế sau", "Chức năng sưởi ấm cho hàng ghế trước", "Lốp xe với bọt hấp thụ tiếng ồn", "Chức năng sưởi ấm cho tựa đầu phía sau", "Cảm biến quét vân tay", "Hệ thống bật/tắt đèn pha chủ động", "Hệ thống treo khí nén AIRMATIC", "Kết nối Apple Carplay", "2 tai nghe không dây cao cấp", "Chức năng hỗ trợ giữ khoảng cách an toàn DISTRONIC", "Lưng ghế sau gập được", "Ghế sau tùy chỉnh bằng điện, có chức năng bộ nhớ", "Hệ thống hỗ trợ đánh lái bánh sau", "Tấm che bảo vệ gầm", "Hệ thống MAGIC VISION CONTROL với cần gạt nước mưa thích ứng & có sưởi", "Chức năng massage bắp chân cho ghế thương gia phía sau", "Camera 360 độ", "Chức năng cửa hít", "Túi khí bên hông cho ghế sau", "Chức năng HANDS-FREE ACCESS", "Hệ thống hiển thị áp suất lốp", "Hệ thống PARKTRONIC", "Màn che nắng kính sau chỉnh điện", "Bàn gấp cho ghế sau", "Gương chiếu hậu chống chói", "Điều hòa khí hậu tự động THERMOTRONIC cho hàng ghế trước", "Hệ thống sưởi & thông gió cho hàng ghế trước", "Hệ thống âm thanh cao cấp Burmester high-end 3D", "Tựa đầu cỡ lớn, điều chỉnh được", "Tấm che nắng 2 bên cho hàng ghế trước", "Cốp đóng mở bằng điện", "Ốp bệ cửa phát sáng", "Head-up Display", "Tay lái đa chức năng bọc da", "Cổng sạc 5V (USB type C) cho hàng ghế sau", "Tủ lạnh cho hàng ghế sau", "PRE-SAFE® impulse", "Các tính năng cho hệ thống giải trí trên xe", "Túi khí phía sau", "Hệ thống báo động chống trộm", "Ghế thương gia", "Khoang sau hạng nhất với 2 ghế độc lập", "Đèn chiếu logo Mercedes", "Hệ thống đèn viền trang trí nội thất chủ động", "kính xe cách âm, cách nhiệt và phản xạ tia hồng ngoại", "Bình nhiên liệu cỡ lớn", "Cửa sau đóng mở bằng điện", "Hệ thống đèn chiếu sáng thích ứng cho khoang hành lý phía sau", "Chức năng massage cho ghế sau", "Hoá chất vá lốp tạm thời TIREFIT", "Cửa sổ trời siêu rộng Panorama", "Bọc trần bằng sợi cao cấp DINAMICA", "Kính cách nhiệt khoang sau màu tối", "Màn che nắng cho cửa sổ hai bên phía sau chỉnh điện", "Khoá dây đai an toàn bằng chrome cao cấp với thiết kế phát sáng đặc biệt", "Hệ thống khóa xe thông minh & khởi động bằng nút bấm KEYLESS-GO", "Hệ thống PRE-SAFE® impulse side", "Thảm sàn cao cấp", "Máy tính bảng điều khiển hệ thống MBUX cho ghế sau", "Hộp số tự động 9 cấp", "Túi khí dây đai", "Chức năng sưởi ấm vô lăng", "Ghế trước có thể gấp gọn", "Hệ thống sưởi & thông gió cho hàng ghế sau"]
    },
    {
        "id": 14,
        "category": "GLE",
        "name": "GLE 53",
        "model": "Citan",
        "color": ["Trắng", "Da Nappa màu đen"],
        "price": "5.679.000.000",
        "year": 2022,
        "material": "Xăng",
        "speed": "250 km/h",
        "size": [5.205, 2.030, 1.838],
        "weight": "2.890 kg",
        "imageUrl": ["https://www.mercedes-benz.com.vn/content/dam/hq/passengercars/cars/gls/mercedes-maybach-gls-x167-pi/overview/modeloverview/09-2022/images/mercedes-maybach-gls-x167-modeloverview-696x392-09-2022.png", "https://imgd-ct.aeplcdn.com/1280x720/n/cw/ec/95489/maybach-gls-exterior-right-front-three-quarter-5.jpeg?isig=0&q=80", "https://images.netdirector.co.uk/gforces-auto/image/upload/q_auto,c_fill,f_auto,fl_lossy/auto-client/9d3c7514d77feab69e74f023b2fc5a30/glsmaybach.png"],
        "chair": 5,
        "intro": "Nhìn tổng thể, GLE mới vẫn áp dụng ngôn ngữ thiết kế Sensual Purity- sự gợi cảm thuần khiết mang đến nét đẹp sang trọng và tinh tế. “Cặp mắt” phía trước của xe sở hữu công nghệ Full-LED với hai dải đèn chạy ban ngày tạo hiệu ứng thị giác mạnh mẽ. Bộ lưới tản nhiệt đã được chia nhỏ thành nhiều phần độc đáo nhằm tạo sự khỏe khoắn. Hốc hút gió của xe trông to và liền mạch hơn nhằm tôn lên nét cá tính, thể thao. Những đường gân dập nổi cơ bắp ở thế hệ trước đã giảm bớt, thay vào đó là sự mềm mại toát lên vẻ thanh lịch. Ấn tượng nhất chính là bộ vành lớn 20 inch AMG giúp chiếc xe tăng thêm phần bề thế.",
        "description": ["Màn hình giải trí 12.3 inch", "Chức năng sạc không dây cho ghế sau", "Tính năng ngắt kích hoạt túi khí trước", "Chức năng sưởi tựa tay cho người lái & hành khách phía trước", "Hệ thống giải trí MBUX High-End cho hàng ghế sau", "Tuỳ chọn cá nhân hoá âm thanh", "Ổ cắm điện 12V", "Bảng đồng hồ kỹ thuật số sau vô lăng với màn hình 12.3-inch và hiệu ứng hiển thị 3D", "Gói ốp gỗ Exclusive", "Hệ thống dẫn đường & định vị vệ tinh toàn cầu GPS tích hợp bản đồ Việt Nam", "Đèn viền nội thất", "chức năng sưởi ghế sau", "Hiển thị thông tin về dây đai của hàng ghế sau", "Chìa khoá thiết kế đặc biệt với viền chrome trang trí", "Kết nối Android Auto", "Hệ thống hỗ trợ giữ làn đường chủ động", "Chức năng điều khiển bằng cử chỉ", "Sách hướng dẫn sử dụng bằng tiếng Việt", "Chức năng sưởi ấm cổ & vai hàng ghế sau", "Tính năng chống trộm được mở rộng", "Chức năng sạc không dây", "Điều hòa khí hậu tự động THERMOTRONIC cho hàng ghế sau", "Hệ thống giải trí MBUX", "Bộ nhớ dành cho ghế sau", "Viền thép không gỉ cao cấp cho khoang hành lý", "DIGITAL LIGHT", "Giá đỡ dây đai an toàn tự động điều chỉnh cho hàng ghế sau", "Chức năng sưởi ấm cho hàng ghế trước", "Lốp xe với bọt hấp thụ tiếng ồn", "Chức năng sưởi ấm cho tựa đầu phía sau", "Cảm biến quét vân tay", "Hệ thống bật/tắt đèn pha chủ động", "Hệ thống treo khí nén AIRMATIC", "Kết nối Apple Carplay", "2 tai nghe không dây cao cấp", "Chức năng hỗ trợ giữ khoảng cách an toàn DISTRONIC", "Lưng ghế sau gập được", "Ghế sau tùy chỉnh bằng điện, có chức năng bộ nhớ", "Hệ thống hỗ trợ đánh lái bánh sau", "Tấm che bảo vệ gầm", "Hệ thống MAGIC VISION CONTROL với cần gạt nước mưa thích ứng & có sưởi", "Chức năng massage bắp chân cho ghế thương gia phía sau", "Camera 360 độ", "Chức năng cửa hít", "Túi khí bên hông cho ghế sau", "Chức năng HANDS-FREE ACCESS", "Hệ thống hiển thị áp suất lốp", "Hệ thống PARKTRONIC", "Màn che nắng kính sau chỉnh điện", "Bàn gấp cho ghế sau", "Gương chiếu hậu chống chói", "Điều hòa khí hậu tự động THERMOTRONIC cho hàng ghế trước", "Hệ thống sưởi & thông gió cho hàng ghế trước", "Hệ thống âm thanh cao cấp Burmester high-end 3D", "Tựa đầu cỡ lớn, điều chỉnh được", "Tấm che nắng 2 bên cho hàng ghế trước", "Cốp đóng mở bằng điện", "Ốp bệ cửa phát sáng", "Head-up Display", "Tay lái đa chức năng bọc da", "Cổng sạc 5V (USB type C) cho hàng ghế sau", "Tủ lạnh cho hàng ghế sau", "PRE-SAFE® impulse", "Các tính năng cho hệ thống giải trí trên xe", "Túi khí phía sau", "Hệ thống báo động chống trộm", "Ghế thương gia", "Khoang sau hạng nhất với 2 ghế độc lập", "Đèn chiếu logo Mercedes", "Hệ thống đèn viền trang trí nội thất chủ động", "kính xe cách âm, cách nhiệt và phản xạ tia hồng ngoại", "Bình nhiên liệu cỡ lớn", "Cửa sau đóng mở bằng điện", "Hệ thống đèn chiếu sáng thích ứng cho khoang hành lý phía sau", "Chức năng massage cho ghế sau", "Hoá chất vá lốp tạm thời TIREFIT", "Cửa sổ trời siêu rộng Panorama", "Bọc trần bằng sợi cao cấp DINAMICA", "Kính cách nhiệt khoang sau màu tối", "Màn che nắng cho cửa sổ hai bên phía sau chỉnh điện", "Khoá dây đai an toàn bằng chrome cao cấp với thiết kế phát sáng đặc biệt", "Hệ thống khóa xe thông minh & khởi động bằng nút bấm KEYLESS-GO", "Hệ thống PRE-SAFE® impulse side", "Thảm sàn cao cấp", "Máy tính bảng điều khiển hệ thống MBUX cho ghế sau", "Hộp số tự động 9 cấp", "Túi khí dây đai", "Chức năng sưởi ấm vô lăng", "Ghế trước có thể gấp gọn", "Hệ thống sưởi & thông gió cho hàng ghế sau"]
    },
    {
        "id": 15,
        "category": "GLE",
        "name": "GLE 450 4MATIC",
        "model": "Citan",
        "color": ["Trắng", "Da Nappa màu đen"],
        "price": "4.359.000.000",
        "year": 2022,
        "material": "Xăng",
        "speed": "250 km/h",
        "size": [5.205, 2.030, 1.838],
        "weight": "2.890 kg",
        "imageUrl": ["https://www.mercedes-benz.com.vn/content/dam/hq/passengercars/cars/gls/mercedes-maybach-gls-x167-pi/overview/modeloverview/09-2022/images/mercedes-maybach-gls-x167-modeloverview-696x392-09-2022.png", "https://imgd-ct.aeplcdn.com/1280x720/n/cw/ec/95489/maybach-gls-exterior-right-front-three-quarter-5.jpeg?isig=0&q=80", "https://images.netdirector.co.uk/gforces-auto/image/upload/q_auto,c_fill,f_auto,fl_lossy/auto-client/9d3c7514d77feab69e74f023b2fc5a30/glsmaybach.png"],
        "chair": 5,
        "intro": "Nhìn tổng thể, GLE mới vẫn áp dụng ngôn ngữ thiết kế Sensual Purity- sự gợi cảm thuần khiết mang đến nét đẹp sang trọng và tinh tế. “Cặp mắt” phía trước của xe sở hữu công nghệ Full-LED với hai dải đèn chạy ban ngày tạo hiệu ứng thị giác mạnh mẽ. Bộ lưới tản nhiệt đã được chia nhỏ thành nhiều phần độc đáo nhằm tạo sự khỏe khoắn. Hốc hút gió của xe trông to và liền mạch hơn nhằm tôn lên nét cá tính, thể thao. Những đường gân dập nổi cơ bắp ở thế hệ trước đã giảm bớt, thay vào đó là sự mềm mại toát lên vẻ thanh lịch. Ấn tượng nhất chính là bộ vành lớn 20 inch AMG giúp chiếc xe tăng thêm phần bề thế.",
        "description": ["Màn hình giải trí 12.3 inch", "Chức năng sạc không dây cho ghế sau", "Tính năng ngắt kích hoạt túi khí trước", "Chức năng sưởi tựa tay cho người lái & hành khách phía trước", "Hệ thống giải trí MBUX High-End cho hàng ghế sau", "Tuỳ chọn cá nhân hoá âm thanh", "Ổ cắm điện 12V", "Bảng đồng hồ kỹ thuật số sau vô lăng với màn hình 12.3-inch và hiệu ứng hiển thị 3D", "Gói ốp gỗ Exclusive", "Hệ thống dẫn đường & định vị vệ tinh toàn cầu GPS tích hợp bản đồ Việt Nam", "Đèn viền nội thất", "chức năng sưởi ghế sau", "Hiển thị thông tin về dây đai của hàng ghế sau", "Chìa khoá thiết kế đặc biệt với viền chrome trang trí", "Kết nối Android Auto", "Hệ thống hỗ trợ giữ làn đường chủ động", "Chức năng điều khiển bằng cử chỉ", "Sách hướng dẫn sử dụng bằng tiếng Việt", "Chức năng sưởi ấm cổ & vai hàng ghế sau", "Tính năng chống trộm được mở rộng", "Chức năng sạc không dây", "Điều hòa khí hậu tự động THERMOTRONIC cho hàng ghế sau", "Hệ thống giải trí MBUX", "Bộ nhớ dành cho ghế sau", "Viền thép không gỉ cao cấp cho khoang hành lý", "DIGITAL LIGHT", "Giá đỡ dây đai an toàn tự động điều chỉnh cho hàng ghế sau", "Chức năng sưởi ấm cho hàng ghế trước", "Lốp xe với bọt hấp thụ tiếng ồn", "Chức năng sưởi ấm cho tựa đầu phía sau", "Cảm biến quét vân tay", "Hệ thống bật/tắt đèn pha chủ động", "Hệ thống treo khí nén AIRMATIC", "Kết nối Apple Carplay", "2 tai nghe không dây cao cấp", "Chức năng hỗ trợ giữ khoảng cách an toàn DISTRONIC", "Lưng ghế sau gập được", "Ghế sau tùy chỉnh bằng điện, có chức năng bộ nhớ", "Hệ thống hỗ trợ đánh lái bánh sau", "Tấm che bảo vệ gầm", "Hệ thống MAGIC VISION CONTROL với cần gạt nước mưa thích ứng & có sưởi", "Chức năng massage bắp chân cho ghế thương gia phía sau", "Camera 360 độ", "Chức năng cửa hít", "Túi khí bên hông cho ghế sau", "Chức năng HANDS-FREE ACCESS", "Hệ thống hiển thị áp suất lốp", "Hệ thống PARKTRONIC", "Màn che nắng kính sau chỉnh điện", "Bàn gấp cho ghế sau", "Gương chiếu hậu chống chói", "Điều hòa khí hậu tự động THERMOTRONIC cho hàng ghế trước", "Hệ thống sưởi & thông gió cho hàng ghế trước", "Hệ thống âm thanh cao cấp Burmester high-end 3D", "Tựa đầu cỡ lớn, điều chỉnh được", "Tấm che nắng 2 bên cho hàng ghế trước", "Cốp đóng mở bằng điện", "Ốp bệ cửa phát sáng", "Head-up Display", "Tay lái đa chức năng bọc da", "Cổng sạc 5V (USB type C) cho hàng ghế sau", "Tủ lạnh cho hàng ghế sau", "PRE-SAFE® impulse", "Các tính năng cho hệ thống giải trí trên xe", "Túi khí phía sau", "Hệ thống báo động chống trộm", "Ghế thương gia", "Khoang sau hạng nhất với 2 ghế độc lập", "Đèn chiếu logo Mercedes", "Hệ thống đèn viền trang trí nội thất chủ động", "kính xe cách âm, cách nhiệt và phản xạ tia hồng ngoại", "Bình nhiên liệu cỡ lớn", "Cửa sau đóng mở bằng điện", "Hệ thống đèn chiếu sáng thích ứng cho khoang hành lý phía sau", "Chức năng massage cho ghế sau", "Hoá chất vá lốp tạm thời TIREFIT", "Cửa sổ trời siêu rộng Panorama", "Bọc trần bằng sợi cao cấp DINAMICA", "Kính cách nhiệt khoang sau màu tối", "Màn che nắng cho cửa sổ hai bên phía sau chỉnh điện", "Khoá dây đai an toàn bằng chrome cao cấp với thiết kế phát sáng đặc biệt", "Hệ thống khóa xe thông minh & khởi động bằng nút bấm KEYLESS-GO", "Hệ thống PRE-SAFE® impulse side", "Thảm sàn cao cấp", "Máy tính bảng điều khiển hệ thống MBUX cho ghế sau", "Hộp số tự động 9 cấp", "Túi khí dây đai", "Chức năng sưởi ấm vô lăng", "Ghế trước có thể gấp gọn", "Hệ thống sưởi & thông gió cho hàng ghế sau"]
    }
]


export const CATEGORIES = [
    {
        "id": 1,
        "name": "S-Class",
        "url": "https://mercedesbenzsaigon.com/wp-content/uploads/2022/06/S450-L-New.png"
    },
    {
        "id": 2,
        "name": "C-Class",
        "url": "https://mercedesbenzsaigon.com/wp-content/uploads/2022/06/icon-c300.png"
    },
    {
        "id": 3,
        "name": "E-Class",
        "url": "https://mercedesbenzsaigon.com/wp-content/uploads/2020/12/E-180-W-removebg-preview.png"
    },
    {
        "id": 4,
        "name": "GLS",
        "url": "https://mercedesbenzsaigon.com/wp-content/uploads/2020/12/GLS-450-EM-1-removebg-preview.png"
    },
    {
        "id": 5,
        "name": "GLE",
        "url": "https://mercedesbenzsaigon.com/wp-content/uploads/2021/12/gls.png"
    },
    {
        "id": 6,
        "name": "GLC",
        "url": "https://mercedesbenzsaigon.com/wp-content/uploads/2022/06/GLC_300_Coupe.png"
    }
]
